name: BisqApps

on:
  push:
    branches:
      - feature/testing_setup
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [androidNode, androidClient, iosClient]

    env:
      # Set up Azul Zulu JDK 17.0.12.fx-zulu or refer to .sdkmanrc
      JAVA_HOME: /usr/lib/jvm/zulu17.32.13-ca-fx-jdk17.0.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Azul Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      # Android setup
      - name: Set up Android SDK
        if: startsWith(matrix.platform, 'android')
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.0

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        working-directory: ./bisqapps
        run: |
            chmod +x gradlew

#          ./gradlew ${{ matrix.app }}:build

#      - name: List contents of bisqapps
#        run: ls -la
#        working-directory: ./bisqapps

      - name: Print Platform
        run: |
          echo "Current platform: ${{ matrix.platform }}"

      - name: Build project
        working-directory: ./bisqapps
        run: ./gradlew build --info

      - name: Run all project tests
        working-directory: ./bisqapps
        run: ./gradlew test

      - name: Run androidClient Tests
        working-directory: ./bisqapps
        if: matrix.platform == 'androidClient'
        run: ./gradlew androidClient:testDebugUnitTest androidClient:connectedDebugAndroidTest

      - name: Run androidNode Tests
        working-directory: ./bisqapps
        if: matrix.platform == 'androidNode'
        run: ./gradlew androidNode:testDebugUnitTest androidNode:connectedDebugAndroidTest

      # iOS setup
      - name: Set up Xcode
        working-directory: ./bisqapps
        if: matrix.platform == 'iosClient'
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          xcodebuild -version

# TODO ios specific and run on emulator
#      - name: Run iOS Tests
#        working-directory: ./bisqapps
#        if: matrix.platform == 'iosClient'
#        run: ./gradlew iosClient:test
