name: BisqApps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- Common Build & Test (runs for all PRs, including forks) ---
  build:
    name: Build & Test (No Secrets)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Azul Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;26.1.10909125"

      - name: Set up Xcode (Mac only)
        if: startsWith(matrix.os, 'macos')
        run: |
          sudo xcode-select -s /Applications/Xcode.app || true
          xcodebuild -version

      - name: Create fake local.properties
        run: |
          echo "KEYSTORE_PATH=/path/to/keystore" > local.properties
          echo "KEYSTORE_PASSWORD=yourKeystorePassword" >> local.properties
          echo "KEY_ALIAS=yourKeyAlias" >> local.properties
          echo "CLI_KEY_ALIAS=yourCliKeyAlias" >> local.properties
          echo "KEY_PASSWORD=yourKeyPassword" >> local.properties
          echo "CLI_KEY_PASSWORD=yourCliKeyPassword" >> local.properties

      - name: Run Android Tests (Ubuntu only)
        if: startsWith(matrix.os, 'ubuntu')
        env:
          CI: true
        run: ./gradlew clean test -x :androidNode:testDebugUnitTest -x :androidNode:testReleaseUnitTest -x :androidNode:test --info

      - name: Android compile-only (Mac only)
        if: startsWith(matrix.os, 'macos')
        run: ./gradlew :androidClient:assembleDebug -x test -x lint

#      TODO seems GH default ci doesn't have support for this
#      - name: Headless Android emulator and run instrumentation tests
#        env:
#          CI: true
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 33
#          target: default
#          arch: x86_64
#          profile: pixel_5
#          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect
#          disable-animations: true
#          script: ./gradlew androidClient:testDebugUnitTest androidClient:connectedDebugAndroidTest

      - name: Generate KMP dummy frameworks (Mac only)
        if: startsWith(matrix.os, 'macos')
        run: |
          ./gradlew :shared:domain:generateDummyFramework :shared:presentation:generateDummyFramework --no-daemon
      - name: Install CocoaPods dependencies (Mac only)
        if: startsWith(matrix.os, 'macos')
        working-directory: iosClient
        run: pod install

      - name: Prebuild KMP frameworks (Intel runner)
        if: startsWith(matrix.os, 'macos') && runner.arch == 'X64'
        run: |
          ./gradlew :shared:domain:linkPodReleaseFrameworkIosX64 :shared:presentation:linkPodReleaseFrameworkIosX64 --no-daemon

      - name: Prebuild KMP frameworks (Apple Silicon runner)
        if: startsWith(matrix.os, 'macos') && runner.arch == 'ARM64'
        run: |
          ./gradlew :shared:domain:linkPodReleaseFrameworkIosSimulatorArm64 :shared:presentation:linkPodReleaseFrameworkIosSimulatorArm64 --no-daemon


      - name: Build iOS Client (Mac only)
        if: startsWith(matrix.os, 'macos')
        run: |
          xcodebuild -workspace iosClient/iosClient.xcworkspace \
            -scheme "iosClient Release" \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Run iOS Tests (x64 simulator for Intel runners)
        if: startsWith(runner.os, 'macOS')
        run: ./gradlew shared:presentation:iosX64Test

  # --- Node-specific Maven build (needs secrets) ---
  node-maven:
    name: Node Build (Needs Secrets)
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository # skip only fork PRs

    env:
      CI: true
      MAVEN_URL: ${{ secrets.MAVEN_URL }}
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Azul Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;26.1.10909125"

      - name: Create fake local.properties
        run: |
          echo "KEYSTORE_PATH=/path/to/keystore" > local.properties
          echo "KEYSTORE_PASSWORD=yourKeystorePassword" >> local.properties
          echo "KEY_ALIAS=yourKeyAlias" >> local.properties
          echo "CLI_KEY_ALIAS=yourCliKeyAlias" >> local.properties
          echo "KEY_PASSWORD=yourKeyPassword" >> local.properties
          echo "CLI_KEY_PASSWORD=yourCliKeyPassword" >> local.properties

      - name: Build Node Project with Maven Secrets
        run: |
          ./gradlew androidNode:clean androidNode:bundleDebug --refresh-dependencies --info
          ./gradlew androidNode:test
